/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.function.Consumer;
import io.github.rdfc.Processor;
import io.github.rdfc.IReader;
import io.github.rdfc.IWriter;

public class Library extends Processor<Library.Args> {

    public Library(Args arguments) {
        super(arguments);
    }

    public boolean someLibraryMethod() {
        return true;
    }

    @Override
    public void init(Consumer arg0) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'init'");
    }

    @Override
    public void produce(Consumer arg0) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'produce'");
    }

    @Override
    public void transform(Consumer arg0) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'transform'");
    }

    public static class Args {
        public String name;
        public IReader reader;
        public IWriter writer;
    }
}
